name: CI

on:
  push:
    branches:
      - "main"
    paths:
      - "randomcoords/**"
      - "tests/**"
      - "pyproject.toml"
      - ".github/workflows/ci.yml"

  pull_request:
    branches:
      - "main"
    paths:
      - "randomcoords/**"
      - "tests/**"
      - "pyproject.toml"
      - ".github/workflows/ci.yml"

jobs:
  test:
    environment: production
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools==80.4.0 wheel==0.45.1
          pip install .[dev]

      - name: Run full validation (format + typecheck + test)
        run: make validate
